name: RJK Codes
baseUrl: https://rjkcodes.site
testUrl: http://localhost:8000
author: RJK
dateFormat: "%a, %b %d %Y"

# Define collections for pages
collections:
  # Generates a collection for each page that has tags.
  # Each tag value gets its own page.
  tags:
    hasProperty: tags

    # Template to use for the each tag value page
    propValueTemplate: tagPage

    # Template to use for the collection ROOT page
    rootTemplate: allTags

    # Set a custom title for the ROOT page of the collection
    # Defaults to the value of 'hasProperty'
    rootTitle: Tags
    addToMenu: true


  # All of the blog posts
  posts:
    propertyEquals:
      property: pageType
      value: post
    template: default

  # All pages you want to add to the main menu
  # 'menu' is special and gets processed last.
  menu:
    propertyEquals:
      property: menu
      value: true
    template: default


# Theme settings
colors:
  foreground: "#005500"
  background: "#fafffa"
  brand: "#f70"
