name: RJK Codes
baseUrl: https://rjkcodes.site
testUrl: http://localhost:8000
author: RJK
dateFormat: "%a, %b %d %Y"

# Define collections for pages
collections:
  tags:
    hasProperty: tags
    template: tagPage
  posts:
    propertyEquals:
      property: pageType
      value: post
    template: default


# Theme settings
colors:
  foreground: "#005500"
  background: "#fafffa"
  brand: "#ff0"
